import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      services: 'Services',
      projects: 'Portfolio',
      contact: 'Contact',
      tagline: 'Digital Agency',
    },
    hero: {
      badge: 'DIGITAL TRANSFORMATION SPECIALISTS',
      title1: 'We craft digital experiences',
      title2: 'your customers remember',
      subtitle: 'Premium web development, software solutions, and digital branding for forward-thinking businesses.',
      cta1: 'Get Free Consultation',
      cta2: 'View Our Services',
      stat1Number: '100+',
      stat1Label: 'Projects Delivered',
      stat2Number: '50+',
      stat2Label: 'Happy Clients',
      stat3Number: '8+',
      stat3Label: 'Years Experience',
      stat4Number: '24/7',
      stat4Label: 'Support',
      slogan: '"Make the world revolve around your brand"',
    },
    home: {
      servicesTitle: 'What We Do Best',
      servicesSubtitle: 'Comprehensive digital solutions tailored to your business needs',
      service1Title: 'Web Development',
      service1Desc: 'Modern and high-performance websites built with the latest technologies. From corporate showcases to complex web applications.',
      service2Title: 'Mobile Applications',
      service2Desc: 'Native and cross-platform applications that offer an exceptional and intuitive user experience.',
      service3Title: 'E-commerce Solutions',
      service3Desc: 'Online sales platforms optimized to maximize your conversions and turn your visitors into customers.',
      service4Title: 'UI/UX Design',
      service4Desc: 'Elegant user interfaces and optimized experiences that combine modern aesthetics and functionality.',
      service5Title: 'SEO Optimization',
      service5Desc: 'SEO strategies to improve your visibility and attract qualified traffic.',
      service6Title: 'Analytics & Insights',
      service6Desc: 'Data analysis to optimize your performance and make informed decisions.',
      exploreServices: 'Explore All Services',
      viewServices: 'View Our Services',
      whyTitle: 'Why Partner With',
      whyHighlight: 'Synapse',
      whyDesc: 'We don\'t just build digital products—we craft experiences that transform businesses and delight users. Our approach combines strategic thinking with technical excellence.',
      whyPoint1: 'Proven track record with 150+ successful projects',
      whyPoint2: 'Expert team of designers, developers, and strategists',
      whyPoint3: 'Agile methodology for faster delivery and flexibility',
      whyPoint4: 'Ongoing support and maintenance post-launch',
      whyPoint5: 'Transparent communication throughout the process',
      learnMore: 'Learn More About Us',
      stat1: '10+',
      stat1Label: 'Years Experience',
      stat2: '40+',
      stat2Label: 'Team Members',
      stat3: '15',
      stat3Label: 'Countries Served',
      stat4: '4.9',
      stat4Label: 'Average Rating',
      ctaTitle: 'Ready to Start Your Project?',
      ctaSubtitle: 'Let\'s discuss how we can help transform your digital presence and achieve your business goals.',
      ctaButton: 'Get In Touch',
      ctaButton1: 'Get In Touch',
      ctaButton2: 'View Portfolio',
      heroStat1: '150+',
      heroStat1Label: 'Projects Delivered',
      heroStat2: '98%',
      heroStat2Label: 'Client Satisfaction',
      heroStat3: '50+',
      heroStat3Label: 'Active Clients',
      heroStat4: '24/7',
      heroStat4Label: 'Support Available',
      trustSectionTitle: 'We Have a Lot of Diversified Projects',
      trustSectionSubtitle: 'Discover why our clients trust us and what they say about our work',
      review1Name: 'Sarah Chen',
      review1Role: 'CEO, TechStart Inc.',
      review1Text: 'Synapse delivered beyond our expectations. Their technical expertise and attention to detail transformed our vision into reality.',
      review2Name: 'Michael Rodriguez',
      review2Role: 'Founder, E-Shop Solutions',
      review2Text: 'Working with Synapse was a game-changer. Our e-commerce platform now handles 10x the traffic with zero downtime.',
      review3Name: 'Emily Watson',
      review3Role: 'Marketing Director, Bloom Agency',
      review3Text: 'The team at Synapse is incredibly professional and responsive. They truly understand modern digital solutions.',
    },
    services: {
      title: 'Our',
      titleHighlight: 'Services',
      subtitle: 'Comprehensive digital solutions tailored to transform your business and accelerate growth.',
      service1Title: 'Web Development',
      service1Desc: 'Custom web applications built with modern frameworks and best practices for optimal performance.',
      service2Title: 'Mobile Solutions',
      service2Desc: 'Native and cross-platform mobile apps that deliver seamless experiences on any device.',
      service3Title: 'Digital Branding',
      service3Desc: 'Complete brand identity design from logo creation to comprehensive brand guidelines.',
      service4Title: 'Product Strategy',
      service4Desc: 'Strategic planning and roadmapping to transform your ideas into successful digital products.',
      service5Title: 'Digital Transformation',
      service5Desc: 'End-to-end digital transformation services to modernize your business operations.',
      service6Title: 'Performance Optimization',
      service6Desc: 'Speed optimization, SEO, and technical improvements for maximum digital impact.',
      learnMore: 'Learn More',
    },
    portfolio: {
      title: 'Featured',
      titleHighlight: 'Work',
      subtitle: 'Explore our portfolio of successful digital products and transformations',
      viewAll: 'View All Projects',
      clientsTitle: 'Trusted By',
      clientsTitleHighlight: 'Industry Leaders',
      clientsSubtitle: 'Partnering with innovative businesses across diverse industries',
    },
    about: {
      badge: 'WHY CHOOSE SYNAPSE',
      title1: 'Building the Future,',
      title2: 'One Connection at a Time',
      desc1: 'Synapse is more than a digital agency. We\'re your strategic partner in digital transformation, combining creative vision with technical excellence to deliver solutions that drive real business results.',
      desc2: 'With over 8 years of experience, we\'ve helped businesses of all sizes navigate the digital landscape. From startups to enterprises, our team brings deep expertise in modern web technologies, user-centered design, and agile development practices.',
      value1Title: 'Precision',
      value1Desc: 'Every pixel, every line of code crafted with meticulous attention to detail.',
      value2Title: 'Collaboration',
      value2Desc: 'We work as an extension of your team, ensuring seamless communication.',
      value3Title: 'Excellence',
      value3Desc: 'Committed to delivering solutions that exceed industry standards.',
      value4Title: 'Innovation',
      value4Desc: 'Always exploring cutting-edge technologies to keep you ahead.',
    },
    process: {
      title: 'How We',
      titleHighlight: 'Work',
      subtitle: 'A proven process that transforms ideas into exceptional digital products',
      step1Title: 'Discovery',
      step1Desc: 'We dive deep into your business, goals, and challenges to understand what success looks like for you.',
      step1Detail1: 'Comprehensive business analysis and competitive research',
      step1Detail2: 'Stakeholder interviews and user persona development',
      step1Detail3: 'Technical requirements gathering and feasibility assessment',
      step1Detail4: 'Market analysis and opportunity identification',
      step1Detail5: 'Define project scope, timeline, and success metrics',
      step2Title: 'Strategy',
      step2Desc: 'Our team develops a comprehensive roadmap with clear milestones, timelines, and deliverables.',
      step2Detail1: 'Information architecture and user flow mapping',
      step2Detail2: 'Technology stack selection and architecture planning',
      step2Detail3: 'Design system creation and UI/UX wireframing',
      step2Detail4: 'Sprint planning and resource allocation',
      step2Detail5: 'Risk assessment and mitigation strategies',
      step3Title: 'Development',
      step3Desc: 'We build your solution using modern tech stacks, agile methodologies, and rigorous quality standards.',
      step3Detail1: 'Agile development with bi-weekly sprints',
      step3Detail2: 'Clean code practices and peer code reviews',
      step3Detail3: 'Automated testing and continuous integration',
      step3Detail4: 'Regular demos and stakeholder feedback sessions',
      step3Detail5: 'Performance optimization and security hardening',
      step4Title: 'Launch & Grow',
      step4Desc: 'We deploy your product and continue to optimize, iterate, and scale based on real-world data.',
      step4Detail1: 'Staged deployment with zero-downtime releases',
      step4Detail2: 'User training and comprehensive documentation',
      step4Detail3: 'Performance monitoring and analytics setup',
      step4Detail4: 'Post-launch support and maintenance',
      step4Detail5: 'Continuous improvement based on user feedback and metrics',
      showDetails: 'Show Details',
      hideDetails: 'Hide Details',
      ctaText: 'Ready to start your digital transformation journey?',
      ctaButton: 'Let\'s Talk',
    },
    trust: {
      title: 'Trusted by',
      titleHighlight: 'Innovators',
      subtitle: 'Join the businesses that trust us with their digital transformation',
      stat1: '98%',
      stat1Label: 'Client Satisfaction',
      stat2: '150+',
      stat2Label: 'Projects Completed',
      stat3: '4.9/5',
      stat3Label: 'Average Rating',
      stat4: '85%',
      stat4Label: 'Repeat Clients',
      testimonial1: 'Synapse transformed our digital presence completely. Their attention to detail and technical expertise is unmatched. Our conversion rates increased by 300%.',
      testimonial1Name: 'Sarah Johnson',
      testimonial1Role: 'CEO, TechStart Inc.',
      testimonial2: 'Working with Synapse was a game-changer. They delivered a world-class product on time and exceeded all our expectations.',
      testimonial2Name: 'Michael Chen',
      testimonial2Role: 'Founder, GrowthLabs',
      testimonial3: 'The team at Synapse brought our vision to life with incredible precision. Their strategic approach and technical skills are outstanding.',
      testimonial3Name: 'Emily Rodriguez',
      testimonial3Role: 'CTO, FinanceFlow',
      clientsLabel: 'Trusted by leading companies',
    },
    contact: {
      title: 'Let\'s Build Something',
      titleHighlight: 'Amazing Together',
      subtitle: 'Ready to transform your digital presence? Get in touch with us and let\'s discuss your project.',
      name: 'Full Name',
      email: 'Email Address',
      company: 'Company Name',
      message: 'Tell us about your project',
      budget: 'Budget Range',
      budgetOption1: 'Under $10k',
      budgetOption2: '$10k - $25k',
      budgetOption3: '$25k - $50k',
      budgetOption4: '$50k+',
      send: 'Send Message',
      sending: 'Sending...',
      phone: 'Phone',
      address: 'Address',
      addressValue: 'Montréal, Québec, Canada',
      hours: 'Business Hours',
      hoursValue: 'Mon - Fri: 9AM - 6PM EST',
      faqTitle: 'Frequently Asked',
      faqTitleHighlight: 'Questions',
    },
    footer: {
      description: 'Premium digital agency specializing in web development, mobile apps, and digital transformation.',
      quickLinks: 'Quick Links',
      home: 'Home',
      about: 'About',
      services: 'Services',
      portfolio: 'Portfolio',
      contact: 'Contact',
      connect: 'Connect With Us',
      rights: 'All rights reserved.',
      slogan: 'Make the world revolve around your brand',
      companyDesc: 'Web development agency & digital solutions based in Montreal, specialized in premium digital transformation.',
      followUs: 'Follow Us',
      copyrightText: '© 2026 Synapse. All rights reserved.',
      quickLinksTitle: 'Quick Links',
      quickLink1: 'Services',
      quickLink2: 'About',
      quickLink3: 'Process',
      quickLink4: 'Projects',
      quickLink5: 'Contact',
      quickLink6: 'FAQs',
      servicesTitle: 'Services',
      service1: 'Web Development',
      service2: 'Mobile Applications',
      service3: 'Digital Branding & Strategy',
      service4: 'E-commerce Solutions',
      service5: 'UI/UX Design',
      service6: 'Analytics & Insights',
      service7: 'On-Site Photography',
      service8: 'Security & Compliance',
      service9: 'Support & Maintenance',
      service10: 'SEO & Digital Marketing Services',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      cookiePolicy: 'Cookie Policy',
      tagline: 'Built with precision and passion',
    },
    chatbot: {
      title: 'Ask Synapse AI',
      subtitle: 'Your Digital Consulting Assistant',
      placeholder: 'Ask me anything about our services...',
      send: 'Send',
      typing: 'Synapse AI is typing...',
      welcome: 'Hello! I\'m Synapse AI, your digital consulting assistant. How can I help you today?',
    },
    aboutPage: {
      badge: 'About Synapse',
      title1: 'Crafting Digital Excellence',
      title2: 'Since 2019',
      subtitle: 'We\'re a team of passionate designers, developers, and strategists dedicated to transforming businesses through innovative digital solutions.',
      stat1: '5+',
      stat1Label: 'Years of Experience',
      stat2: '15+',
      stat2Label: 'Active Clients',
      stat3: '5+',
      stat3Label: 'Years Partnership',
      tagline: 'Premium digital solutions without the premium price tag.',
      taglineDesc: 'From on-site photography to SEO-ready full-stack development, we manage the details so you can focus on growing your business.',
      
      // Our Story & Vision
      storyVisionTitle: 'Our Story & Vision',
      storyVisionP1: 'Synapse represents the point where meaningful connections are formed. In the human brain, a synapse is where signals connect and create understanding.',
      storyVisionP2: 'We see digital work the same way — where strategy, creativity and technology come together to build strong brands, effective websites and scalable digital businesses.',
      storyVisionP3: 'We believe great digital experiences are created through thoughtful collaboration, clear communication and purposeful design.',
      
      // Mission
      missionTitle: 'Our Mission',
      missionDesc: 'Our mission is to help businesses grow by closing the gap between their goals and their digital presence. We create practical, well-engineered digital solutions that deliver real value to our clients and support long-term business success.',
      
      // Philosophy
      philosophyTitle: 'Our Philosophy',
      philosophyDesc: 'We believe strong digital products are built on human connection. By working closely with our clients and providing honest, meaningful support, we aim to build lasting partnerships that create positive outcomes for both businesses and the people behind them.',
      
      // Experience & Expertise
      experienceTitle: 'Experience & Expertise',
      noteTitle: 'Proven Track Record',
      noteDesc: 'While the company officially launched in January 2026, our team has been working on personal and collaborative projects since 2019.',
      exp1Title: 'Digital Development',
      exp1Desc: 'We specialize in full-stack website and digital product development, combining design, front-end and back-end engineering into complete solutions.',
      exp2Title: 'Proven Track Record',
      exp2Desc: 'Although Synapse officially launched in January 2026, our team has been delivering personal and collaborative digital projects since 2019.',
      exp3Title: 'Long-Term Partnership',
      exp3Desc: 'Our founders have worked together in the digital space for more than five years, building products across multiple industries and project types.',
      
      // What We Do
      whatWeDoTitle: 'What We Do',
      whatWeDo1Title: 'Modernize Digital Presence',
      whatWeDo1Desc: 'We help businesses improve and evolve their online presence through modern design, reliable technology and performance-focused development.',
      whatWeDo2Title: 'Enable Business Growth',
      whatWeDo2Desc: 'Our solutions are designed to support real business growth by aligning creative direction with scalable technical architecture.',
      
      // Why Choose Us
      whyChooseTitle: 'Why Choose Us',
      whyChooseSubtitle: 'The Synapse Advantage',
      advantage1Title: 'On-Site Brand Photography',
      advantage1Desc: 'We offer a premium on-site photography service, providing professional visual content that strengthens your brand and digital presence.',
      advantage2Title: 'SEO-Ready Development',
      advantage2Desc: 'Every project is built with search engine optimization best practices from the start, ensuring strong technical foundations for visibility and performance.',
      advantage3Title: 'Complimentary Initial Hosting',
      advantage3Desc: 'We provide hosting at no cost during the initial project phase to support a smooth launch and transition.',
      advantage4Title: 'Complimentary Design Mock-ups',
      advantage4Desc: 'Clients receive professional design mock-ups before development begins, allowing you to clearly visualize your digital experience.',
      advantage5Title: 'Accessible and Competitive Pricing',
      advantage5Desc: 'We deliver high-quality digital solutions at fair and transparent pricing, designed to be accessible for growing businesses.',
      advantage6Title: 'Sponsor and Partner Network',
      advantage6Desc: 'Through our trusted network of partners and sponsors, we are able to offer specialized services and exclusive benefits to our clients when required.',
      
      ctaTitle: 'Let\'s Build Something Amazing Together',
      ctaSubtitle: 'Ready to start your digital transformation journey? We\'d love to hear about your project.',
      ctaButton: 'Get In Touch',
    },
    servicesPage: {
      badge: 'Our Services',
      title1: 'Digital Solutions That',
      title2: 'Drive Results',
      subtitle: 'From strategy to execution, we offer comprehensive digital services tailored to your business goals and user needs.',
      getStarted: 'Get Started',
      // Web Development
      webDevTitle: 'Full-Stack Web Development',
      webDevDesc: 'Our development team will create a complimentary mockup of your digital website, which includes two free pages: the homepage and the contact page. Should you choose to continue with our services, we offer comprehensive full-stack solutions tailored to your needs.',
      webDevFeature1: 'Front-end and back-end development',
      webDevFeature2: 'Database design and management',
      webDevFeature3: 'API integration',
      webDevFeature4: 'Responsive and mobile-friendly design',
      webDevFeature5: 'E-commerce functionality',
      webDevFeature6: 'Hosting and maintenance',
      webDevFeature7: 'Performance optimization and security',
      techTitle: 'Technologies We Use',
      // Mobile Development
      mobileTitle: 'Mobile App Development',
      mobileDesc: 'Native and cross-platform mobile applications that deliver seamless experiences on iOS and Android. We build apps that users love, with intuitive interfaces and powerful functionality.',
      mobileFeature1: 'Native iOS & Android Apps',
      mobileFeature2: 'Cross-Platform Solutions',
      mobileFeature3: 'App UI/UX Design',
      mobileFeature4: 'Backend & API Integration',
      mobileFeature5: 'Push Notifications',
      mobileFeature6: 'App Maintenance & Updates',
      platformTitle: 'Platform Expertise',
      platformIOS: 'iOS Development',
      platformIOSDesc: 'Native Swift & SwiftUI apps',
      platformAndroid: 'Android Development',
      platformAndroidDesc: 'Native Kotlin & Jetpack Compose',
      platformCross: 'Cross-Platform',
      platformCrossDesc: 'React Native & Flutter',
      platformASO: 'App Store Optimization',
      platformASODesc: 'Launch & marketing support',
      // Digital Branding
      brandingTitle: 'Digital Branding & Design',
      brandingDesc: 'Create a memorable brand identity and stunning visual experiences that resonate with your audience. We combine strategic thinking with creative excellence to build brands that stand out.',
      brandingFeature1: 'Brand Identity & Logo Design',
      brandingFeature2: 'UI/UX Design',
      brandingFeature3: 'Design Systems',
      brandingFeature4: 'Visual Design & Graphics',
      brandingFeature5: 'Brand Guidelines',
      brandingFeature6: 'Marketing Collateral',
      designServicesTitle: 'Design Services',
      designService1: 'User Research',
      designService1Desc: 'Understanding your audience',
      designService2: 'Wireframing',
      designService2Desc: 'Structure and flow planning',
      designService3: 'Prototyping',
      designService3Desc: 'Interactive design mockups',
      designService4: 'Visual Design',
      designService4Desc: 'Beautiful, on-brand interfaces',
      // Digital Strategy
      strategyTitle: 'Digital Strategy & Consulting',
      strategyDesc: 'Strategic guidance to navigate digital transformation and achieve your business objectives. We help you make informed decisions backed by data and industry expertise.',
      strategyFeature1: 'Digital Transformation Strategy',
      strategyFeature2: 'Product & Business Strategy',
      strategyFeature3: 'Technology Consulting',
      strategyFeature4: 'User Experience Strategy',
      strategyFeature5: 'Analytics & Optimization',
      strategyFeature6: 'Growth & Marketing Strategy',
      strategicServicesTitle: 'Strategic Services',
      strategicService1: 'Digital Roadmapping',
      strategicService1Desc: 'Strategic planning & execution',
      strategicService2: 'Product Strategy',
      strategicService2Desc: 'Feature prioritization & MVP',
      strategicService3: 'Market Analysis',
      strategicService3Desc: 'Competitive research',
      strategicService4: 'Growth Strategy',
      strategicService4Desc: 'Scaling your digital presence',
      // E-commerce
      ecommerceTitle: 'E-commerce Solutions',
      ecommerceDesc: 'Online sales platforms optimized to maximize your conversions and turn your visitors into customers. Build your online store with cutting-edge technology.',
      ecommerceFeature1: 'Custom E-commerce Platforms',
      ecommerceFeature2: 'Secure Payment Processing',
      ecommerceFeature3: 'Payment Gateway Integration',
      ecommerceFeature4: 'Inventory Management',
      ecommerceFeature5: 'Conversion Rate Optimization',
      ecommerceFeature6: 'Multi-currency Support',
      ecommerceFeaturesTitle: 'E-commerce Features',
      ecommerceF1: 'Product Catalog',
      ecommerceF1Desc: 'Advanced product management',
      ecommerceF2: 'Shopping Cart',
      ecommerceF2Desc: 'Seamless checkout experience',
      ecommerceF3: 'Order Management',
      ecommerceF3Desc: 'Track & fulfill orders',
      ecommerceF4: 'Analytics',
      ecommerceF4Desc: 'Sales insights & reporting',
      // UI/UX Design
      uiuxTitle: 'UI/UX Design',
      uiuxDesc: 'Elegant user interfaces and optimized experiences that combine modern aesthetics and functionality. Creating intuitive designs that users love.',
      uiuxFeature1: 'User Research & Testing',
      uiuxFeature2: 'Interface Design',
      uiuxFeature3: 'User Experience Strategy',
      uiuxFeature4: 'Design Systems',
      uiuxFeature5: 'Accessibility (WCAG)',
      uiuxFeature6: 'Responsive Design',
      designProcessTitle: 'Design Process',
      designProcess1: 'Research & Discovery',
      designProcess1Desc: 'Understanding user needs',
      designProcess2: 'Wireframing',
      designProcess2Desc: 'Information architecture',
      designProcess3: 'Visual Design',
      designProcess3Desc: 'Beautiful interfaces',
      designProcess4: 'Prototyping',
      designProcess4Desc: 'Interactive mockups',
      // SEO & Digital Marketing
      seoTitle: 'SEO & Digital Marketing',
      seoDesc: 'We help your website get noticed, attract visitors, and turn them into customers through comprehensive digital marketing strategies. All-in-one strategy to grow your online presence and drive results.',
      seoFeature1: 'SEO: Get found on Google with optimized content',
      seoFeature2: 'Content Marketing: Engage visitors with blogs & videos',
      seoFeature3: 'Social Media: Promote your brand and connect',
      seoFeature4: 'Paid Advertising: Boost traffic with Google & social ads',
      seoFeature5: 'Email Marketing: Nurture leads and inform customers',
      seoFeature6: 'Conversion Optimization: Improve visitor actions',
      seoServicesTitle: 'Marketing Services',
      seoService1: 'Analytics & Reporting',
      seoService1Desc: 'Track performance and refine strategies',
      seoService2: 'Reputation Management',
      seoService2Desc: 'Build trust with reviews',
      seoService3: 'Technical SEO',
      seoService3Desc: 'Technical improvements for rankings',
      seoService4: 'Campaign Management',
      seoService4Desc: 'End-to-end marketing campaigns',
      // Analytics
      analyticsTitle: 'Analytics & Insights',
      analyticsDesc: 'Data analysis to optimize your performance and make informed decisions. Turn data into actionable insights that drive business growth.',
      analyticsFeature1: 'Web Analytics Setup',
      analyticsFeature2: 'Conversion Tracking',
      analyticsFeature3: 'User Behavior Analysis',
      analyticsFeature4: 'Performance Monitoring',
      analyticsFeature5: 'Custom Reporting',
      analyticsFeature6: 'Data-Driven Recommendations',
      analyticsToolsTitle: 'Analytics Tools',
      analyticsTool1: 'Google Analytics',
      analyticsTool1Desc: 'Track user behavior',
      analyticsTool2: 'Heatmaps',
      analyticsTool2Desc: 'Visual engagement data',
      analyticsTool3: 'A/B Testing',
      analyticsTool3Desc: 'Optimize conversions',
      analyticsTool4: 'Custom Dashboards',
      analyticsTool4Desc: 'Real-time insights',
      // Additional Services
      additionalTitle: 'Additional Services',
      additionalSubtitle: 'Complementary services to support your digital success',
      additional1Title: 'On-Site Photography',
      additional1Short: 'Professional photos of your products, team, and workspace',
      additional1Desc: 'Bring your website to life with professional photos taken right at your business location. Our photographer captures high-quality images of your products, team, and space to make your website look authentic and engaging. Perfect for showcasing your products/services, highlighting your team, and creating visuals for your website, social media, and marketing materials.',
      additional2Title: 'Security & Compliance',
      additional2Short: 'Protect your data with robust security measures',
      additional2Desc: 'Robust security measures and compliance with industry standards to protect your data and users.',
      additional3Title: 'Support & Maintenance',
      additional3Short: 'Keep your digital products running smoothly',
      additional3Desc: 'Ongoing support, updates, and optimization to keep your digital products running smoothly.',
      additional4Title: 'SEO & Digital Marketing Services',
      additional4Short: 'Boost your online presence and attract more customers',
      additional4Desc: 'As a small business, getting noticed online is essential. We provide practical, results-driven SEO and digital marketing solutions designed for businesses with limited time and resources.',
      additional4What: 'What We Offer:',
      additional4Item1: '• Local SEO Optimization: Make sure your business shows up on Google when customers search for your services.',
      additional4Item2: '• On-Page SEO: Improve your website\'s meta titles, descriptions, headings, and content for better search engine ranking.',
      additional4Item3: '• Google Business Profile Setup & Optimization: Help your business stand out in local searches and maps.',
      additional4Item4: '• Analytics & Insights: Track website traffic, customer behavior, and campaign performance with Google Analytics.',
      additional4Item5: '• Basic Digital Marketing Support: Email signup forms, social media feed integration, and marketing tools setup.',
      additional4Why: 'Why Work With Us:',
      additional4Benefit1: '✓ Tailored strategies for small businesses',
      additional4Benefit2: '✓ Affordable solutions without unnecessary complexity',
      additional4Benefit3: '✓ Ongoing support to keep your website performing at its best',
      additional4Benefit4: '💡 Optional Add-On: Monthly SEO maintenance and performance reporting to ensure your website stays visible and competitive.',
      learnMore: 'Learn More',
      showLess: 'Show Less',
      // Process
      processTitle: 'How We Work',
      processSubtitle: 'A proven process that transforms ideas into exceptional digital products',
      process1Number: '1',
      process1Title: 'Discovery',
      process1Desc: 'We dive deep into your business, goals, and challenges to understand what success looks like for you.',
      process1Detail: 'In this initial phase, we conduct comprehensive research to understand your business objectives, target audience, competitive landscape, and technical requirements. We collaborate closely with you to define project goals, success metrics, and key deliverables.',
      process2Number: '2',
      process2Title: 'Strategy',
      process2Desc: 'Our team develops a comprehensive roadmap with clear milestones, timelines, and deliverables.',
      process2Detail: 'Based on our discovery findings, we create a detailed project plan that outlines the technical architecture, design direction, development phases, and timeline. This roadmap ensures everyone is aligned and sets clear expectations for the entire project journey.',
      process3Number: '3',
      process3Title: 'Development',
      process3Desc: 'We build your solution using modern tech stacks, agile methodologies, and rigorous quality standards.',
      process3Detail: 'Our development team brings the strategy to life through iterative sprints, continuous testing, and regular check-ins. We maintain code quality, ensure responsive design, and keep you informed throughout the build process with demos and updates.',
      process4Number: '4',
      process4Title: 'Launch & Grow',
      process4Desc: 'We deploy your product and continue to optimize, iterate, and scale based on real-world data.',
      process4Detail: 'After launch, we monitor performance, gather user feedback, and implement improvements. Our ongoing support ensures your digital product continues to evolve with your business needs and delivers long-term value.',
      processShowDetails: 'Show Details',
      processHideDetails: 'Hide Details',
      processCTA: 'Ready to start your digital transformation journey?',
      processCTAButton: 'Let\'s Talk',
      // CTA
      ctaTitle: 'Ready to Get Started?',
      ctaSubtitle: 'Let\'s discuss your project and find the perfect solution for your needs.',
      ctaButton1: 'Schedule Consultation',
      ctaButton2: 'View Our Services',
    },
    projectsPage: {
      badge: 'Our Work',
      title1: 'Projects That',
      title2: 'Make an Impact',
      subtitle: 'Explore our portfolio of successful digital projects across various industries and technologies.',
      // Categories
      categoryAll: 'All',
      categoryWeb: 'Web Development',
      categoryMobile: 'Mobile Apps',
      categoryBranding: 'Branding',
      categoryEcommerce: 'E-commerce',
      // Projects
      project1Title: 'FinTech Dashboard',
      project1Category: 'Web Development',
      project1Desc: 'A comprehensive financial analytics platform with real-time data visualization and reporting.',
      project1Result: '+250% user engagement',
      project2Title: 'E-commerce Platform',
      project2Category: 'E-commerce',
      project2Desc: 'Modern online shopping experience with seamless checkout and inventory management.',
      project2Result: '+180% conversion rate',
      project3Title: 'Health & Fitness App',
      project3Category: 'Mobile Apps',
      project3Desc: 'Cross-platform mobile app for tracking workouts, nutrition, and wellness goals.',
      project3Result: '500K+ downloads',
      project4Title: 'TechStart Branding',
      project4Category: 'Branding',
      project4Desc: 'Complete brand identity for an innovative tech startup, including logo, design system, and guidelines.',
      project4Result: '100% brand recognition',
      project5Title: 'Real Estate Portal',
      project5Category: 'Web Development',
      project5Desc: 'Property listing platform with advanced search, virtual tours, and CRM integration.',
      project5Result: '10K+ listings',
      project6Title: 'Food Delivery App',
      project6Category: 'Mobile Apps',
      project6Desc: 'On-demand food delivery platform connecting customers with local restaurants.',
      project6Result: '50K+ orders/month',
      project7Title: 'Fashion Boutique',
      project7Category: 'E-commerce',
      project7Desc: 'Luxury fashion e-commerce with personalized recommendations and AR try-on features.',
      project7Result: '+300% sales growth',
      project8Title: 'SaaS Product Redesign',
      project8Category: 'Branding',
      project8Desc: 'Complete UI/UX overhaul for a B2B SaaS platform, improving usability and visual appeal.',
      project8Result: '+150% user satisfaction',
      project9Title: 'Learning Management System',
      project9Category: 'Web Development',
      project9Desc: 'Educational platform with course management, video streaming, and progress tracking.',
      project9Result: '100K+ students',
      // Stats
      statsTitle: 'Proven Track Record',
      statsSubtitle: 'Numbers that demonstrate our commitment to excellence',
      stat1Number: '150+',
      stat1Label: 'Projects Delivered',
      stat2Number: '98%',
      stat2Label: 'Client Satisfaction',
      stat3Number: '15',
      stat3Label: 'Countries Served',
      stat4Number: '2M+',
      stat4Label: 'Users Reached',
      // CTA
      ctaTitle: 'Let\'s Create Your Success Story',
      ctaSubtitle: 'Ready to bring your vision to life? Let\'s discuss how we can help you achieve your goals.',
      ctaButton1: 'Start Your Project',
      ctaButton2: 'Explore Services',
      // Sponsorship
      sponsorshipTitle: 'Proudly Supported By',
      sponsorshipSubtitle: 'Industry leaders and professionals who trust Synapse to elevate their digital presence',
      partnershipsBadge: 'PARTNERSHIPS',
      supportingSynapse: 'SUPPORTING SYNAPSE',
      clickToLearnMore: 'Click to learn more',
      clickToFlipBack: 'Click to flip back',
      // Sponsor 1
      sponsor1Service: 'Boxing Coach - Team Canada',
      sponsor1Desc: 'Omar Alieh brings world-class boxing training to aspiring athletes across Canada. He chose Synapse to create a professional digital presence that reflects his dedication to excellence and helps him reach more athletes looking for elite coaching.',
      sponsor1Why: 'Partnered with Synapse to build a modern platform that showcases his training programs and connects with the next generation of boxing champions.',
      // Sponsor 2
      sponsor2Service: 'Premium Barbershop & Car Wash',
      sponsor2Desc: 'Barbershop Principale offers premium grooming services with the convenience of car wash service. They partnered with Synapse to modernize their booking system and expand their digital reach in the Laval community.',
      sponsor2Why: 'Chose Synapse for seamless online booking integration and a stylish digital presence that matches their premium service quality.',
      // Sponsor 3
      sponsor3Service: 'Financial Security Advisor',
      sponsor3Desc: 'Yassine Akkabi provides expert financial planning and security services to help clients build secure futures. He trusted Synapse to create a professional digital platform that conveys trust and expertise to potential clients.',
      sponsor3Why: 'Selected Synapse to establish a credible online presence that reflects his professional expertise and makes it easy for clients to connect.',
      // Sponsor 4
      sponsor4Service: 'Powder Coating & Metal Painting',
      sponsor4Desc: 'CP Powder Coating specializes in professional powder coating and metal painting services for automotive and industrial applications. They collaborated with Synapse to showcase their portfolio and streamline customer inquiries.',
      sponsor4Why: 'Partnered with Synapse to build a visual portfolio that demonstrates their craftsmanship and simplifies the quote request process.',
      // Sponsor 5
      sponsor5Service: 'Marketing Agency',
      sponsor5Desc: 'Ramzi Kerouicha delivers comprehensive digital marketing and brand strategy services. He chose Synapse to develop a cutting-edge digital platform that showcases his marketing expertise and attracts high-value clients.',
      sponsor5Why: 'Collaborated with Synapse to create a sophisticated online presence that demonstrates his marketing prowess and converts visitors into clients.',
    },
    contactPage: {
      badge: 'Get In Touch',
      title1: 'Let\'s Start a',
      title2: 'Conversation',
      subtitle: 'Have a project in mind? We\'d love to hear about it. Send us a message and we\'ll respond within 24 hours.',
      formTitle: 'Send us a message',
      formSubtitle: 'Fill out the form below and we\'ll get back to you shortly.',
      formNameLabel: 'Full Name *',
      formNamePlaceholder: 'John Doe',
      formEmailLabel: 'Email Address *',
      formEmailPlaceholder: 'john@example.com',
      formCompanyLabel: 'Company Name',
      formCompanyPlaceholder: 'Your Company',
      formPhoneLabel: 'Phone Number',
      formPhonePlaceholder: '+1 (555) 123-4567',
      formServiceLabel: 'Service Interested In *',
      formServicePlaceholder: 'Select a service',
      formServiceWeb: 'Web Development',
      formServiceMobile: 'Mobile App Development',
      formServiceBranding: 'Digital Branding',
      formServiceStrategy: 'Digital Strategy',
      formServiceEcommerce: 'E-commerce',
      formServiceOther: 'Other',
      formBudgetLabel: 'Project Budget',
      formBudgetPlaceholder: 'Select budget range',
      formBudget1: '$5,000 - $10,000',
      formBudget2: '$10,000 - $25,000',
      formBudget3: '$25,000 - $50,000',
      formBudget4: '$50,000+',
      formMessageLabel: 'Project Details *',
      formMessagePlaceholder: 'Tell us about your project...',
      formSubmitButton: 'Send Message',
      formSuccessTitle: 'Message Sent!',
      formSuccessSubtitle: 'We\'ll get back to you within 24 hours.',
      emailTitle: 'Email Us',
      emailContent: 'contact@madebysynapse.com',
      emailDescription: 'Send us an email anytime',
      phoneTitle: '',
      phoneContent: '',
      phoneDescription: '',
      locationTitle: 'Visit Us',
      locationContent: 'Montréal, Québec',
      locationDescription: 'Come say hello at our office',
      hoursTitle: 'Business Hours',
      hoursMonFri: 'Monday - Friday',
      hoursMonFriTime: '9:00 AM - 6:00 PM',
      hoursSat: 'Saturday',
      hoursSatTime: '10:00 AM - 4:00 PM',
      hoursSun: 'Sunday',
      hoursSunTime: 'Closed',
      hoursEmergency: '24/7 emergency support available',
      mapTitle: 'Our Location',
      mapSubtitle: 'Montréal, Québec',
      faqBadge: 'FAQ',
      faqTitle1: 'Frequently Asked',
      faqTitle2: 'Questions',
      faqSubtitle: 'Find answers to common questions about our services and how we work',
      faqQ1: 'What services does Synapse provide?',
      faqA1: 'Synapse is a full-service digital agency specializing in web and software development, UI/UX design, branding, and digital transformation. We help businesses design, build, and scale digital products that are reliable, secure, and tailored to real business needs.',
      faqQ2: 'What types of businesses do you work with?',
      faqA2: 'We work with startups, small and medium-sized businesses, and growing companies across different industries. Whether you are launching a new product or improving an existing system, we adapt our process to your goals, budget, and technical requirements.',
      faqQ3: 'How does a project usually start?',
      faqA3: 'Every project starts with a short discovery call. We take time to understand your objectives, challenges, and users, and then propose a clear solution, timeline, and next steps before any development begins.',
      faqQ4: 'How long does a typical project take?',
      faqA4: 'Project timelines vary depending on complexity and scope. A simple website or redesign can take a few weeks, while larger custom software solutions may take several months. After our initial consultation, we provide a detailed timeline so you always know what to expect.',
      faqQ5: 'How much do your services cost?',
      faqA5: 'Our pricing is based on the scope, features, and technical complexity of each project. We do not use one-size-fits-all packages. After reviewing your needs, we provide a transparent and tailored proposal.',
      faqQ6: 'Will I be involved during the project?',
      faqA6: 'Yes. We believe in close collaboration and clear communication. You will receive regular updates, design previews, and opportunities to provide feedback throughout the entire process.',
      faqQ7: 'Do you offer ongoing support after the project is finished?',
      faqA7: 'Yes. We offer maintenance and support options to ensure your website or digital product remains secure, stable, and up to date after launch.',
      faqQ8: 'Can you work with our existing website or system?',
      faqA8: 'Absolutely. We can improve, redesign, or extend existing platforms, websites, and software systems, while minimizing disruption to your business operations.',
      faqQ9: 'Do you help with design as well as development?',
      faqA9: 'Yes. Our team handles both design and development, ensuring that your digital product is visually strong, user-friendly, and technically robust.',
      faqQ10: 'How can I get started with Synapse?',
      faqA10: 'Simply fill out the contact form above and tell us about your project. Our team will get back to you to schedule a short consultation and discuss the best way forward.',
    },
  },
  fr: {
    nav: {
      home: 'Accueil',
      about: 'À Propos',
      services: 'Services',
      projects: 'Portefeuille',
      contact: 'Contact',
      tagline: 'Agence Numérique',
    },
    hero: {
      badge: 'SPÉCIALISTES EN TRANSFORMATION NUMÉRIQUE',
      title1: 'Nous créons des expériences numériques',
      title2: 'que vos clients se souviennent',
      subtitle: 'Développement web premium, solutions logicielles et image de marque numérique pour les entreprises avant-gardistes.',
      cta1: 'Consultation Gratuite',
      cta2: 'Voir Nos Services',
      stat1Number: '100+',
      stat1Label: 'Projets Livrés',
      stat2Number: '50+',
      stat2Label: 'Clients Satisfaits',
      stat3Number: '8+',
      stat3Label: 'Années d\'Expérience',
      stat4Number: '24/7',
      stat4Label: 'Support',
      slogan: '"Faites tourner le monde autour de votre marque"',
    },
    home: {
      servicesTitle: 'Ce que nous faisons de meilleur',
      servicesSubtitle: 'Solutions numériques complètes adaptées à vos besoins d\'entreprise',
      service1Title: 'Développement web',
      service1Desc: 'Sites web modernes et performants construits avec les dernières technologies. Du showcase d\'entreprise aux applications web complexes.',
      service2Title: 'Applications mobiles',
      service2Desc: 'Applications natives et multiplateformes offrant une expérience utilisateur exceptionnelle et intuitive.',
      service3Title: 'Solutions e-commerce',
      service3Desc: 'Plateformes de vente en ligne optimisées pour maximiser vos conversions et transformer vos visiteurs en clients.',
      service4Title: 'Design UI/UX',
      service4Desc: 'Interfaces utilisateur élégantes et expériences optimisées combinant esthétique moderne et fonctionnalité.',
      service5Title: 'Optimisation SEO',
      service5Desc: 'Stratégies SEO pour améliorer votre visibilité et attirer du trafic qualifié.',
      service6Title: 'Analyse & insights',
      service6Desc: 'Analyse de données pour optimiser vos performances et prendre des décisions éclairées.',
      exploreServices: 'Explorer tous les services',
      viewServices: 'Voir nos services',
      whyTitle: 'Pourquoi collaborer avec',
      whyHighlight: 'Synapse',
      whyDesc: 'Nous ne construisons pas seulement des produits numériques—nous créons des expériences qui transforment les entreprises et ravissent les utilisateurs. Notre approche combine la pensée stratégique avec l\'excellence technique.',
      whyPoint1: 'Historique probant avec 150+ projets réussis',
      whyPoint2: 'Équipe d\'experts en design, développement et stratégie',
      whyPoint3: 'Méthodologie agile pour une livraison plus rapide et de la flexibilité',
      whyPoint4: 'Support et maintenance post-lancement',
      whyPoint5: 'Communication transparente tout au long du processus',
      learnMore: 'En savoir plus sur nous',
      stat1: '10+',
      stat1Label: 'Années d\'Expérience',
      stat2: '40+',
      stat2Label: 'Membres de l\'Équipe',
      stat3: '15',
      stat3Label: 'Pays Servis',
      stat4: '4.9',
      stat4Label: 'Note Moyenne',
      ctaTitle: 'Prêt à commencer votre projet?',
      ctaSubtitle: 'Discutons de la façon dont nous pouvons vous aider à transformer votre présence numérique et atteindre vos objectifs d\'entreprise.',
      ctaButton: 'Nous contacter',
      ctaButton1: 'Nous contacter',
      ctaButton2: 'Voir le portefeuille',
      heroStat1: '150+',
      heroStat1Label: 'Projets livrés',
      heroStat2: '98%',
      heroStat2Label: 'Satisfaction des clients',
      heroStat3: '50+',
      heroStat3Label: 'Clients actifs',
      heroStat4: '24/7',
      heroStat4Label: 'Support disponible',
      trustSectionTitle: 'Nous avons beaucoup de projets diversifiés',
      trustSectionSubtitle: 'Découvrez pourquoi nos clients nous font confiance et ce qu\'ils disent de notre travail',
      review1Name: 'Sarah Chen',
      review1Role: 'PDG, TechStart Inc.',
      review1Text: 'Synapse a dépassé nos attentes. Leur expertise technique et leur souci du détail ont transformé notre vision en réalité.',
      review2Name: 'Michael Rodriguez',
      review2Role: 'Fondateur, E-Shop Solutions',
      review2Text: 'Travailler avec Synapse a tout changé. Notre plateforme e-commerce gère maintenant 10 fois plus de trafic sans interruption.',
      review3Name: 'Emily Watson',
      review3Role: 'Directrice Marketing, Bloom Agency',
      review3Text: 'L\'équipe de Synapse est incroyablement professionnelle et réactive. Ils comprennent vraiment les solutions numériques modernes.',
    },
    services: {
      title: 'Nos',
      titleHighlight: 'services',
      subtitle: 'Solutions numériques complètes adaptées pour transformer votre entreprise et accélérer la croissance.',
      service1Title: 'Développement web',
      service1Desc: 'Applications web personnalisées construites avec des frameworks modernes et les meilleures pratiques pour une performance optimale.',
      service2Title: 'Solutions mobiles',
      service2Desc: 'Applications mobiles natives et multiplateformes offrant des expériences fluides sur tous les appareils.',
      service3Title: 'Image de marque numérique',
      service3Desc: 'Conception complète d\'identité de marque, de la création de logo aux directives de marque complètes.',
      service4Title: 'Stratégie de produit',
      service4Desc: 'Planification stratégique et feuille de route pour transformer vos idées en produits numériques réussis.',
      service5Title: 'Transformation numérique',
      service5Desc: 'Services de transformation numérique de bout en bout pour moderniser vos opérations commerciales.',
      service6Title: 'Optimisation des performances',
      service6Desc: 'Optimisation de la vitesse, SEO et améliorations techniques pour un impact numérique maximal.',
      learnMore: 'En savoir plus',
    },
    portfolio: {
      title: 'Travaux',
      titleHighlight: 'en vedette',
      subtitle: 'Découvrez notre portfolio de produits numériques et transformations réussis',
      viewAll: 'Voir tous les projets',
      clientsTitle: 'Approuvé par les',
      clientsTitleHighlight: 'leaders de l\'industrie',
      clientsSubtitle: 'En partenariat avec des entreprises innovantes dans divers secteurs',
    },
    about: {
      badge: 'POURQUOI CHOISIR SYNAPSE',
      title1: 'Construisons l\'avenir,',
      title2: 'une connexion à la fois',
      desc1: 'Synapse est plus qu\'une agence numérique. Nous sommes votre partenaire stratégique en transformation numérique, combinant vision créative avec excellence technique pour livrer des solutions qui génèrent des résultats réels pour votre entreprise.',
      desc2: 'Avec plus de 8 ans d\'expérience, nous avons aidé des entreprises de toutes tailles à naviguer dans le paysage numérique. Que ce soit des startups ou des entreprises, notre équipe apporte une expertise approfondie en technologies web modernes, conception centrée sur l\'utilisateur et pratiques de développement agile.',
      value1Title: 'Précision',
      value1Desc: 'Chaque pixel, chaque ligne de code est conçu avec une attention méticuleuse aux détails.',
      value2Title: 'Collaboration',
      value2Desc: 'Nous travaillons comme une extension de votre équipe, assurant une communication fluide.',
      value3Title: 'Excellence',
      value3Desc: 'Engagés à livrer des solutions qui dépassent les normes de l\'industrie.',
      value4Title: 'Innovation',
      value4Desc: 'Nous explorons constamment les technologies de pointe pour vous garder en avance.',
    },
    process: {
      title: 'Comment nous',
      titleHighlight: 'travaillons',
      subtitle: 'Un processus éprouvé qui transforme les idées en produits numériques exceptionnels',
      step1Title: 'Découverte',
      step1Desc: 'Nous plongeons profondément dans votre entreprise, vos objectifs et vos défis pour comprendre ce que signifie le succès pour vous.',
      step1Detail1: 'Analyse d\'entreprise complète et recherche concurrentielle',
      step1Detail2: 'Entretiens avec les parties prenantes et développement de personae utilisateurs',
      step1Detail3: 'Collecte des exigences techniques et évaluation de faisabilité',
      step1Detail4: 'Analyse du marché et identification des opportunités',
      step1Detail5: 'Définir l\'étendue du projet, le calendrier et les métriques de succès',
      step2Title: 'Stratégie',
      step2Desc: 'Notre équipe développe un plan de route complet avec des jalons clairs, des calendriers et des livrables.',
      step2Detail1: 'Architecture d\'information et cartographie des flux utilisateur',
      step2Detail2: 'Sélection de la pile technologique et planification de l\'architecture',
      step2Detail3: 'Création du système de conception et wireframing UI/UX',
      step2Detail4: 'Planification des sprints et allocation des ressources',
      step2Detail5: 'Évaluation des risques et stratégies de mitigation',
      step3Title: 'Développement',
      step3Desc: 'Nous construisons votre solution en utilisant des piles technologiques modernes, des méthodologies agiles et des normes de qualité rigoureuses.',
      step3Detail1: 'Développement agile avec des sprints bi-hebdomadaires',
      step3Detail2: 'Pratiques de code propre et revues de code par pairs',
      step3Detail3: 'Tests automatisés et intégration continue',
      step3Detail4: 'Démonstrations régulières et sessions de feedback avec les parties prenantes',
      step3Detail5: 'Optimisation des performances et renforcement de la sécurité',
      step4Title: 'Lancement & Croissance',
      step4Desc: 'Nous déployons votre produit et continuons à optimiser, itérer et échelonner en fonction des données du monde réel.',
      step4Detail1: 'Déploiement en plusieurs étapes avec des mises à jour sans temps d\'arrêt',
      step4Detail2: 'Formation des utilisateurs et documentation complète',
      step4Detail3: 'Mise en place de la surveillance des performances et de l\'analyse',
      step4Detail4: 'Support et maintenance post-lancement',
      step4Detail5: 'Améliorations continues basées sur les commentaires des utilisateurs et les métriques',
      showDetails: 'Afficher les détails',
      hideDetails: 'Masquer les détails',
      ctaText: 'Prêt à commencer votre parcours de transformation numérique ?',
      ctaButton: 'Parlons-en',
    },
    trust: {
      title: 'Fait confiance à',
      titleHighlight: 'les innovateurs',
      subtitle: 'Rejoignez les entreprises qui nous font confiance pour leur transformation numérique',
      stat1: '98%',
      stat1Label: 'Satisfaction des clients',
      stat2: '150+',
      stat2Label: 'Projets terminés',
      stat3: '4.9/5',
      stat3Label: 'Note moyenne',
      stat4: '85%',
      stat4Label: 'Clients récurrents',
      testimonial1: 'Synapse a transformé complètement notre présence numérique. Leur attention aux détails et leur expertise technique sont sans égal. Nos taux de conversion ont augmenté de 300%.',
      testimonial1Name: 'Sarah Johnson',
      testimonial1Role: 'PDG, TechStart Inc.',
      testimonial2: 'Travailler avec Synapse a été un changement de jeu. Ils ont livré un produit de classe mondiale à temps et ont dépassé toutes nos attentes.',
      testimonial2Name: 'Michael Chen',
      testimonial2Role: 'Fondateur, GrowthLabs',
      testimonial3: 'L\'équipe de Synapse a rendu notre vision réalité avec une précision incroyable. Leur approche stratégique et leurs compétences techniques sont exceptionnelles.',
      testimonial3Name: 'Emily Rodriguez',
      testimonial3Role: 'CTO, FinanceFlow',
      clientsLabel: 'Fait confiance aux entreprises leaders',
    },
    contact: {
      title: 'Construisons quelque chose',
      titleHighlight: 'd\'incroyable ensemble',
      subtitle: 'Prêt à transformer votre présence numérique? Contactez-nous et discutons de votre projet.',
      name: 'Nom complet',
      email: 'Adresse email',
      company: 'Nom de l\'entreprise',
      message: 'Parlez-nous de votre projet',
      budget: 'Fourchette de budget',
      budgetOption1: 'Moins de 10k$',
      budgetOption2: '10k$ - 25k$',
      budgetOption3: '25k$ - 50k$',
      budgetOption4: '50k$+',
      send: 'Envoyer le message',
      sending: 'Envoi en cours...',
      phone: 'Téléphone',
      address: 'Adresse',
      addressValue: 'Montréal, Québec, Canada',
      hours: 'Heures d\'ouverture',
      hoursValue: 'Lun - Ven: 9h - 18h EST',
      faqTitle: 'Questions',
      faqTitleHighlight: 'fréquemment posées',
    },
    footer: {
      description: 'Agence numérique premium spécialisée dans le développement web, les applications mobiles et la transformation numérique.',
      quickLinks: 'Liens rapides',
      home: 'Accueil',
      about: 'À propos',
      services: 'Services',
      portfolio: 'Portefeuille',
      contact: 'Contact',
      connect: 'Connectez-vous',
      rights: 'Tous droits réservés.',
      slogan: 'Faites tourner le monde autour de votre marque',
      companyDesc: 'Agence de développement web & solutions numériques basée à Montréal, spécialisée dans la transformation numérique de pointe.',
      followUs: 'Suivez-nous',
      copyrightText: '© 2026 Synapse. Tous droits réservés.',
      quickLinksTitle: 'Liens rapides',
      quickLink1: 'Services',
      quickLink2: 'À propos',
      quickLink3: 'Processus',
      quickLink4: 'Projets',
      quickLink5: 'Contact',
      quickLink6: 'FAQs',
      servicesTitle: 'Services',
      service1: 'Développement web',
      service2: 'Applications mobiles',
      service3: 'Image de marque & stratégie',
      service4: 'Solutions e-commerce',
      service5: 'Design UI/UX',
      service6: 'Analyse & insights',
      service7: 'Photographie sur place',
      service8: 'Sécurité & conformité',
      service9: 'Support & maintenance',
      service10: 'Services de SEO & marketing numérique',
      privacyPolicy: 'Politique de confidentialité',
      termsOfService: 'Conditions d\'utilisation',
      cookiePolicy: 'Politique de cookies',
      tagline: 'Construit avec précision et passion',
    },
    chatbot: {
      title: 'Demandez à Synapse IA',
      subtitle: 'Votre assistant de consultation numérique',
      placeholder: 'Posez-moi des questions sur nos services...',
      send: 'Envoyer',
      typing: 'Synapse IA est en train d\'écrire...',
      welcome: 'Bonjour! Je suis Synapse IA, votre assistant de consultation numérique. Comment puis-je vous aider aujourd\'hui?',
    },
    aboutPage: {
      badge: 'À propos de Synapse',
      title1: 'Créer l\'excellence numérique',
      title2: 'depuis 2019',
      subtitle: 'Nous sommes une équipe de designers, développeurs et stratèges passionnés, dédiés à transformer les entreprises grâce à des solutions numériques innovantes.',
      stat1: '5+',
      stat1Label: 'Ans d\'expérience',
      stat2: '15+',
      stat2Label: 'Clients actifs',
      stat3: '5+',
      stat3Label: 'Ans de partenariat',
      tagline: 'Solutions numériques premium sans le prix premium.',
      taglineDesc: 'De la photographie sur site au développement full-stack optimisé pour le SEO, nous gérons les détails pour que vous puissiez vous concentrer sur la croissance de votre entreprise.',
      
      // Notre Histoire & Vision
      storyVisionTitle: 'Notre histoire & vision',
      storyVisionP1: 'Synapse représente le point où se forment des connexions significatives. Dans le cerveau humain, une synapse est l\'endroit où les signaux se connectent et créent la compréhension.',
      storyVisionP2: 'Nous voyons le travail numérique de la même manière — où la stratégie, la créativité et la technologie se rejoignent pour construire des marques fortes, des sites web efficaces et des entreprises numériques évolutives.',
      storyVisionP3: 'Nous croyons que de grandes expériences numériques sont créées grâce à une collaboration réfléchie, une communication claire et un design intentionnel.',
      
      // Mission
      missionTitle: 'Notre mission',
      missionDesc: 'Notre mission est d\'aider les entreprises à croître en comblant l\'écart entre leurs objectifs et leur présence numérique. Nous créons des solutions numériques pratiques et bien conçues qui offrent une réelle valeur à nos clients et soutiennent le succès commercial à long terme.',
      
      // Philosophie
      philosophyTitle: 'Notre philosophie',
      philosophyDesc: 'Nous croyons que les produits numériques solides sont construits sur la connexion humaine. En travaillant étroitement avec nos clients et en fournissant un soutien honnête et significatif, nous visons à construire des partenariats durables qui créent des résultats positifs pour les entreprises et les personnes qui les soutiennent.',
      
      // Expérience & Expertise
      experienceTitle: 'Expérience & expertise',
      noteTitle: 'Historique prouvé',
      noteDesc: 'Bien que l\'entreprise ait officiellement été lancée en janvier 2026, notre équipe travaille sur des projets personnels et collaboratifs depuis 2019.',
      exp1Title: 'Développement numérique',
      exp1Desc: 'Nous nous spécialisons dans le développement de sites web et de produits numériques full-stack, combinant design, ingénierie front-end et back-end en solutions complètes.',
      exp2Title: 'Historique prouvé',
      exp2Desc: 'Bien que Synapse ait officiellement été lancé en janvier 2026, notre équipe livre des projets numériques personnels et collaboratifs depuis 2019.',
      exp3Title: 'Partenariat à long terme',
      exp3Desc: 'Nos fondateurs travaillent ensemble dans l\'espace numérique depuis plus de cinq ans, construisant des produits à travers de multiples industries et types de projets.',
      
      // Ce Que Nous Faisons
      whatWeDoTitle: 'Ce que nous faisons',
      whatWeDo1Title: 'Moderniser la présence numérique',
      whatWeDo1Desc: 'Nous aidons les entreprises à améliorer et faire évoluer leur présence en ligne grâce à un design moderne, une technologie fiable et un développement axé sur la performance.',
      whatWeDo2Title: 'Favoriser la croissance des entreprises',
      whatWeDo2Desc: 'Nos solutions sont conçues pour soutenir la croissance réelle des entreprises en alignant la direction créative avec une architecture technique évolutive.',
      
      // Pourquoi Nous Choisir
      whyChooseTitle: 'Pourquoi nous choisir',
      whyChooseSubtitle: 'L\'avantage Synapse',
      advantage1Title: 'Photographie de marque sur site',
      advantage1Desc: 'Nous offrons un service de photographie sur site premium, fournissant du contenu visuel professionnel qui renforce votre marque et votre présence numérique.',
      advantage2Title: 'Développement optimisé SEO',
      advantage2Desc: 'Chaque projet est construit avec les meilleures pratiques d\'optimisation pour les moteurs de recherche dès le départ, assurant des fondations techniques solides pour la visibilité et la performance.',
      advantage3Title: 'Hébergement initial gratuit',
      advantage3Desc: 'Nous fournissons l\'hébergement gratuitement pendant la phase initiale du projet pour soutenir un lancement et une transition en douceur.',
      advantage4Title: 'Maquettes de design gratuites',
      advantage4Desc: 'Les clients reçoivent des maquettes de design professionnelles avant le début du développement, vous permettant de visualiser clairement votre expérience numérique.',
      advantage5Title: 'Prix accessibles et compétitifs',
      advantage5Desc: 'Nous livrons des solutions numériques de haute qualité à des prix justes et transparents, conçus pour être accessibles aux entreprises en croissance.',
      advantage6Title: 'Réseau de sponsors et partenaires',
      advantage6Desc: 'Grâce à notre réseau de confiance de partenaires et sponsors, nous sommes en mesure d\'offrir des services spécialisés et des avantages exclusifs à nos clients lorsque nécessaire.',
      
      ctaTitle: 'Construisons quelque chose d\'incroyable ensemble',
      ctaSubtitle: 'Prêt à commencer votre parcours de transformation numérique? Nous aimerions en savoir plus sur votre projet.',
      ctaButton: 'Nous contacter',
    },
    servicesPage: {
      badge: 'Nos services',
      title1: 'Solutions numériques qui',
      title2: 'génèrent des résultats',
      subtitle: 'Du début à la fin, nous offrons des services numériques complets adaptés à vos objectifs d\'entreprise et aux besoins de vos utilisateurs.',
      getStarted: 'Commencer',
      // Développement Web
      webDevTitle: 'Développement web full-stack',
      webDevDesc: 'Notre équipe de développement créera une maquette gratuite de votre site web numérique, qui comprend deux pages gratuites : la page d\'accueil et la page de contact. Si vous choisissez de continuer avec nos services, nous offrons des solutions full-stack complètes adaptées à vos besoins.',
      webDevFeature1: 'Développement front-end et back-end',
      webDevFeature2: 'Conception et gestion de bases de données',
      webDevFeature3: 'Intégration d\'API',
      webDevFeature4: 'Design réactif et adapté aux mobiles',
      webDevFeature5: 'Fonctionnalité e-commerce',
      webDevFeature6: 'Hébergement et maintenance',
      webDevFeature7: 'Optimisation des performances et sécurité',
      techTitle: 'Technologies que nous utilisons',
      // Développement Mobile
      mobileTitle: 'Développement d\'applications mobiles',
      mobileDesc: 'Applications mobiles natives et multiplateformes qui offrent des expériences fluides sur iOS et Android. Nous créons des applications que les utilisateurs aiment, avec des interfaces intuitives et des fonctionnalités puissantes.',
      mobileFeature1: 'Applications iOS & Android natives',
      mobileFeature2: 'Solutions multiplateformes',
      mobileFeature3: 'Conception UI/UX de l\'application',
      mobileFeature4: 'Backend & intégration d\'API',
      mobileFeature5: 'Notifications push',
      mobileFeature6: 'Maintenance et mises à jour de l\'application',
      platformTitle: 'Expertise en plateformes',
      platformIOS: 'Développement iOS',
      platformIOSDesc: 'Applications Swift & SwiftUI natives',
      platformAndroid: 'Développement Android',
      platformAndroidDesc: 'Applications Kotlin & Jetpack Compose natives',
      platformCross: 'Multiplateformes',
      platformCrossDesc: 'React Native & Flutter',
      platformASO: 'Optimisation de la présence sur les magasins d\'applications',
      platformASODesc: 'Soutien à la mise en place et au marketing',
      // Branding Numérique
      brandingTitle: 'Branding numérique & design',
      brandingDesc: 'Créez une identité de marque mémorable et des expériences visuelles impressionnantes qui résonnent avec votre public. Nous combinons la pensée stratégique avec l\'excellence créative pour construire des marques qui se démarquent.',
      brandingFeature1: 'Identité de marque & design de logo',
      brandingFeature2: 'Design UI/UX',
      brandingFeature3: 'Systèmes de conception',
      brandingFeature4: 'Design visuel & graphisme',
      brandingFeature5: 'Directives de marque',
      brandingFeature6: 'Matériel de marketing',
      designServicesTitle: 'Services de design',
      designService1: 'Recherche utilisateur',
      designService1Desc: 'Comprendre votre public',
      designService2: 'Wireframing',
      designService2Desc: 'Planification de la structure et du flux',
      designService3: 'Prototypage',
      designService3Desc: 'Mockups de design interactifs',
      designService4: 'Design visuel',
      designService4Desc: 'Interfaces belles et conformes à la marque',
      // Stratégie Numérique
      strategyTitle: 'Stratégie & conseil numérique',
      strategyDesc: 'Guidance stratégique pour naviguer dans la transformation numérique et atteindre vos objectifs d\'entreprise. Nous vous aidons à prendre des décisions éclairées appuyées sur des données et l\'expertise de l\'industrie.',
      strategyFeature1: 'Stratégie de transformation numérique',
      strategyFeature2: 'Stratégie de produit & entreprise',
      strategyFeature3: 'Conseil en technologies',
      strategyFeature4: 'Stratégie d\'expérience utilisateur',
      strategyFeature5: 'Analyse & optimisation',
      strategyFeature6: 'Stratégie de croissance & marketing',
      strategicServicesTitle: 'Services stratégiques',
      strategicService1: 'Cartographie numérique',
      strategicService1Desc: 'Planification & exécution stratégiques',
      strategicService2: 'Stratégie de produit',
      strategicService2Desc: 'Priorisation des fonctionnalités & MVP',
      strategicService3: 'Analyse de marché',
      strategicService3Desc: 'Recherche concurrentielle',
      strategicService4: 'Stratégie de croissance',
      strategicService4Desc: 'Échelonnement de votre présence numérique',
      // E-commerce
      ecommerceTitle: 'Solutions e-commerce',
      ecommerceDesc: 'Plateformes de vente en ligne optimisées pour maximiser vos conversions et transformer vos visiteurs en clients. Construisez votre magasin en ligne avec des technologies de pointe.',
      ecommerceFeature1: 'Plateformes e-commerce personnalisées',
      ecommerceFeature2: 'Traitement de paiement sécurisé',
      ecommerceFeature3: 'Intégration de porte-monnaie de paiement',
      ecommerceFeature4: 'Gestion de stock',
      ecommerceFeature5: 'Optimisation du taux de conversion',
      ecommerceFeature6: 'Support multimonnaie',
      ecommerceFeaturesTitle: 'Fonctionnalités e-commerce',
      ecommerceF1: 'Catalogue de produits',
      ecommerceF1Desc: 'Gestion avancée des produits',
      ecommerceF2: 'Panier d\'achat',
      ecommerceF2Desc: 'Expérience de checkout fluide',
      ecommerceF3: 'Gestion des commandes',
      ecommerceF3Desc: 'Suivi & exécution des commandes',
      ecommerceF4: 'Analyse',
      ecommerceF4Desc: 'Insights et rapports de vente',
      // Design UI/UX
      uiuxTitle: 'Design UI/UX',
      uiuxDesc: 'Interfaces utilisateur élégantes et expériences optimisées qui combinent esthétique moderne et fonctionnalité. Créer des designs intuitifs que les utilisateurs aiment.',
      uiuxFeature1: 'Recherche & test utilisateur',
      uiuxFeature2: 'Design d\'interface',
      uiuxFeature3: 'Stratégie d\'expérience utilisateur',
      uiuxFeature4: 'Systèmes de conception',
      uiuxFeature5: 'Accessibilité (WCAG)',
      uiuxFeature6: 'Design responsive',
      designProcessTitle: 'Processus de design',
      designProcess1: 'Recherche & découverte',
      designProcess1Desc: 'Comprendre les besoins des utilisateurs',
      designProcess2: 'Wireframing',
      designProcess2Desc: 'Architecture d\'information',
      designProcess3: 'Design visuel',
      designProcess3Desc: 'Interfaces belles',
      designProcess4: 'Prototypage',
      designProcess4Desc: 'Mockups interactifs',
      // SEO & Marketing Numérique
      seoTitle: 'SEO & marketing numérique',
      seoDesc: 'Nous aidons votre site web à se faire remarquer, attirer des visiteurs et les convertir en clients grâce à des stratégies de marketing numérique complètes. Stratégie tout-en-un pour développer votre présence en ligne et générer des résultats.',
      seoFeature1: 'SEO: Être trouvé sur Google avec du contenu optimisé',
      seoFeature2: 'Marketing de contenu: Engager avec blogs & vidéos',
      seoFeature3: 'Réseaux sociaux: Promouvoir votre marque et connecter',
      seoFeature4: 'Publicité payante: Booster le trafic avec Google & social',
      seoFeature5: 'Email marketing: Nourrir les prospects et informer',
      seoFeature6: 'Optimisation de conversion: Améliorer les actions',
      seoServicesTitle: 'Services marketing',
      seoService1: 'Analyse & rapports',
      seoService1Desc: 'Suivre et affiner les stratégies',
      seoService2: 'Gestion de réputation',
      seoService2Desc: 'Bâtir la confiance avec les avis',
      seoService3: 'SEO technique',
      seoService3Desc: 'Améliorations techniques pour classements',
      seoService4: 'Gestion de campagnes',
      seoService4Desc: 'Campagnes marketing complètes',
      // Analyse
      analyticsTitle: 'Analyse & insights',
      analyticsDesc: 'Analyse de données pour optimiser vos performances et prendre des décisions éclairées. Transformer les données en insights actionnables qui stimulent la croissance de l\'entreprise.',
      analyticsFeature1: 'Mise en place de l\'analyse web',
      analyticsFeature2: 'Suivi des conversions',
      analyticsFeature3: 'Analyse du comportement des utilisateurs',
      analyticsFeature4: 'Surveillance des performances',
      analyticsFeature5: 'Rapports personnalisés',
      analyticsFeature6: 'Recommandations basées sur les données',
      analyticsToolsTitle: 'Outils d\'analyse',
      analyticsTool1: 'Google Analytics',
      analyticsTool1Desc: 'Suivre le comportement des utilisateurs',
      analyticsTool2: 'Cartes de chaleur',
      analyticsTool2Desc: 'Données d\'engagement visuel',
      analyticsTool3: 'Tests A/B',
      analyticsTool3Desc: 'Optimiser les conversions',
      analyticsTool4: 'Tableaux de bord personnalisés',
      analyticsTool4Desc: 'Insights en temps réel',
      // Services Complémentaires
      additionalTitle: 'Services complémentaires',
      additionalSubtitle: 'Services complémentaires pour soutenir votre succès numérique',
      additional1Title: 'Photographie sur site',
      additional1Short: 'Photos professionnelles de vos produits, équipe et espace',
      additional1Desc: 'Donnez vie à votre site web avec des photos professionnelles prises directement dans votre établissement. Notre photographe capture des images de haute qualité de vos produits, votre équipe et votre espace pour rendre votre site web authentique et engageant. Parfait pour présenter vos produits/services, mettre en valeur votre équipe et cr��er des visuels pour votre site web, réseaux sociaux et matériel marketing.',
      additional2Title: 'Sécurité & conformité',
      additional2Short: 'Protégez vos données avec des mesures de sécurité robustes',
      additional2Desc: 'Mesures de sécurité robustes et conformité avec les normes de l\'industrie pour protéger vos données et vos utilisateurs.',
      additional3Title: 'Support & maintenance',
      additional3Short: 'Maintenez vos produits numériques en bon fonctionnement',
      additional3Desc: 'Support continu, mises à jour et optimisation pour maintenir vos produits numériques en bon état de fonctionnement.',
      additional4Title: 'Services SEO & marketing numérique',
      additional4Short: 'Boostez votre présence en ligne et attirez plus de clients',
      additional4Desc: 'Pour une petite entreprise, se faire remarquer en ligne est essentiel. Nous fournissons des solutions SEO et marketing numérique pratiques et axées sur les résultats, conçues pour les entreprises avec un temps et des ressources limités.',
      additional4What: 'Ce que nous offrons:',
      additional4Item1: '• Optimisation SEO Locale: Assurez-vous que votre entreprise apparaît sur Google lorsque les clients recherchent vos services.',
      additional4Item2: '• SEO On-Page: Améliorez les méta-titres, descriptions, titres et contenu de votre site pour un meilleur classement.',
      additional4Item3: '• Configuration et Optimisation du Profil Google Business: Aidez votre entreprise à se démarquer dans les recherches et cartes locales.',
      additional4Item4: '• Analyses et Insights: Suivez le trafic du site, le comportement des clients et les performances des campagnes avec Google Analytics.',
      additional4Item5: '• Support Marketing Numérique de Base: Formulaires d\'inscription email, intégration des flux de réseaux sociaux et configuration des outils marketing.',
      additional4Why: 'Pourquoi travailler avec nous:',
      additional4Benefit1: '✓ Stratégies personnalisées pour petites entreprises',
      additional4Benefit2: '✓ Solutions abordables sans complexité inutile',
      additional4Benefit3: '✓ Support continu pour maintenir les performances de votre site',
      additional4Benefit4: '💡 Module Optionnel: Maintenance SEO mensuelle et rapports de performance pour garantir que votre site reste visible et compétitif.',
      learnMore: 'En savoir plus',
      showLess: 'Voir moins',
      // Process
      processTitle: 'Comment nous travaillons',
      processSubtitle: 'Un processus éprouvé qui transforme les idées en produits numériques exceptionnels',
      process1Number: '1',
      process1Title: 'Découverte',
      process1Desc: 'Nous plongeons profondément dans votre entreprise, vos objectifs et vos défis pour comprendre à quoi ressemble le succès pour vous.',
      process1Detail: 'Dans cette phase initiale, nous effectuons des recherches approfondies pour comprendre vos objectifs commerciaux, votre public cible, votre paysage concurrentiel et vos exigences techniques. Nous collaborons étroitement avec vous pour définir les objectifs du projet, les mesures de succès et les livrables clés.',
      process2Number: '2',
      process2Title: 'Stratégie',
      process2Desc: 'Notre équipe développe une feuille de route complète avec des jalons, des délais et des livrables clairs.',
      process2Detail: 'Sur la base de nos découvertes, nous créons un plan de projet détaillé qui décrit l\'architecture technique, la direction du design, les phases de développement et le calendrier. Cette feuille de route garantit que tout le monde est aligné et établit des attentes claires pour l\'ensemble du parcours du projet.',
      process3Number: '3',
      process3Title: 'Développement',
      process3Desc: 'Nous construisons votre solution en utilisant des technologies modernes, des méthodologies agiles et des normes de qualité rigoureuses.',
      process3Detail: 'Notre équipe de développement donne vie à la stratégie grâce à des sprints itératifs, des tests continus et des points de contrôle réguliers. Nous maintenons la qualité du code, assurons un design réactif et vous tenons informé tout au long du processus avec des démos et des mises à jour.',
      process4Number: '4',
      process4Title: 'Lancement & croissance',
      process4Desc: 'Nous déployons votre produit et continuons à optimiser, itérer et évoluer en fonction des données réelles.',
      process4Detail: 'Après le lancement, nous surveillons les performances, recueillons les commentaires des utilisateurs et mettons en œuvre des améliorations. Notre support continu garantit que votre produit numérique continue d\'évoluer avec les besoins de votre entreprise et offre une valeur à long terme.',
      processShowDetails: 'Afficher les détails',
      processHideDetails: 'Masquer les détails',
      processCTA: 'Prêt à commencer votre parcours de transformation numérique?',
      processCTAButton: 'Discutons',
      // CTA
      ctaTitle: 'Prêt à commencer?',
      ctaSubtitle: 'Discutons de votre projet et trouvons la solution parfaite pour vos besoins.',
      ctaButton1: 'Planifier une consultation',
      ctaButton2: 'Voir nos services',
    },
    projectsPage: {
      badge: 'Notre travail',
      title1: 'Projets qui',
      title2: 'ont un impact',
      subtitle: 'Explorez notre portfolio de projets numériques réussis dans diverses industries et technologies.',
      // Categories
      categoryAll: 'Tous',
      categoryWeb: 'Développement web',
      categoryMobile: 'Applications mobiles',
      categoryBranding: 'Branding',
      categoryEcommerce: 'E-commerce',
      // Projects
      project1Title: 'Tableau de bord FinTech',
      project1Category: 'Développement web',
      project1Desc: 'Une plateforme complète d\'analyse financière avec visualisation de données en temps réel et rapports.',
      project1Result: '+250% d\'engagement des utilisateurs',
      project2Title: 'Plateforme e-commerce',
      project2Category: 'E-commerce',
      project2Desc: 'Expérience d\'achat en ligne moderne avec paiement fluide et gestion de l\'inventaire.',
      project2Result: '+180% de taux de conversion',
      project3Title: 'Application santé & fitness',
      project3Category: 'Applications mobiles',
      project3Desc: 'Application mobile multiplateforme pour suivre les entraînements, la nutrition et les objectifs de bien-être.',
      project3Result: '500K+ téléchargements',
      project4Title: 'Branding TechStart',
      project4Category: 'Branding',
      project4Desc: 'Identité de marque complète pour une startup technologique innovante, incluant logo, système de conception et directives.',
      project4Result: '100% de reconnaissance de la marque',
      project5Title: 'Portail immobilier',
      project5Category: 'Développement web',
      project5Desc: 'Plateforme d\'annonces immobilières avec recherche avancée, visites virtuelles et intégration CRM.',
      project5Result: '10K+ annonces',
      project6Title: 'Application de livraison de nourriture',
      project6Category: 'Applications mobiles',
      project6Desc: 'Plateforme de livraison de nourriture à la demande connectant les clients aux restaurants locaux.',
      project6Result: '50K+ commandes/mois',
      project7Title: 'Boutique de mode',
      project7Category: 'E-commerce',
      project7Desc: 'E-commerce de mode de luxe avec recommandations personnalisées et fonctionnalités d\'essayage en RA.',
      project7Result: '+300% de croissance des ventes',
      project8Title: 'Refonte de produit SaaS',
      project8Category: 'Branding',
      project8Desc: 'Refonte complète UI/UX pour une plateforme SaaS B2B, améliorant l\'utilisabilité et l\'attrait visuel.',
      project8Result: '+150% de satisfaction des utilisateurs',
      project9Title: 'Système de Gestion de l\'Apprentissage',
      project9Category: 'Développement web',
      project9Desc: 'Plateforme éducative avec gestion de cours, diffusion vidéo et suivi des progrès.',
      project9Result: '100K+ étudiants',
      // Stats
      statsTitle: 'Bilan prouvé',
      statsSubtitle: 'Des chiffres qui démontrent notre engagement envers l\'excellence',
      stat1Number: '150+',
      stat1Label: 'Projets livrés',
      stat2Number: '98%',
      stat2Label: 'Satisfaction client',
      stat3Number: '15',
      stat3Label: 'Pays servis',
      stat4Number: '2M+',
      stat4Label: 'Utilisateurs atteints',
      // CTA
      ctaTitle: 'Créons votre histoire de succès',
      ctaSubtitle: 'Prêt à donner vie à votre vision? Discutons de la façon dont nous pouvons vous aider à atteindre vos objectifs.',
      ctaButton1: 'Démarrer votre projet',
      ctaButton2: 'Explorer les services',
      // Sponsorship
      sponsorshipTitle: 'Fièrement soutenus par',
      sponsorshipSubtitle: 'Leaders de l\'industrie et professionnels qui font confiance à Synapse pour élever leur présence numérique',
      partnershipsBadge: 'PARTENARIATS',
      supportingSynapse: 'SOUTIENT SYNAPSE',
      clickToLearnMore: 'Cliquez pour en savoir plus',
      clickToFlipBack: 'Cliquez pour retourner',
      // Sponsor 1
      sponsor1Service: 'Entraîneur de boxe - Équipe Canada',
      sponsor1Desc: 'Omar Alieh offre un entraînement de boxe de classe mondiale aux athlètes aspirants à travers le Canada. Il a choisi Synapse pour créer une présence numérique professionnelle qui reflète son dévouement à l\'excellence et l\'aide à rejoindre plus d\'athlètes.',
      sponsor1Why: 'Partenariat avec Synapse pour construire une plateforme moderne qui présente ses programmes d\'entraînement et connecte avec la prochaine génération de champions de boxe.',
      // Sponsor 2
      sponsor2Service: 'Salon de coiffure et lave-auto premium',
      sponsor2Desc: 'Barbershop Principale offre des services de toilettage premium avec la commodité du lave-auto. Ils se sont associés à Synapse pour moderniser leur système de réservation et élargir leur portée numérique dans la communauté de Laval.',
      sponsor2Why: 'A choisi Synapse pour une intégration de réservation en ligne fluide et une présence numérique élégante qui correspond à la qualité de leurs services premium.',
      // Sponsor 3
      sponsor3Service: 'Conseiller en sécurité financière',
      sponsor3Desc: 'Yassine Akkabi fournit des services experts de planification financière et de sécurité pour aider les clients à construire un avenir sécurisé. Il a fait confiance à Synapse pour créer une plateforme numérique professionnelle qui transmet confiance et expertise.',
      sponsor3Why: 'A sélectionné Synapse pour établir une présence en ligne crédible qui reflète son expertise professionnelle et facilite la connexion avec les clients.',
      // Sponsor 4
      sponsor4Service: 'Revêtement en poudre et peinture métallique',
      sponsor4Desc: 'CP Powder Coating se spécialise dans le revêtement en poudre professionnel et la peinture métallique pour applications automobiles et industrielles. Ils ont collaboré avec Synapse pour présenter leur portfolio et simplifier les demandes des clients.',
      sponsor4Why: 'Partenariat avec Synapse pour construire un portfolio visuel qui démontre leur savoir-faire et simplifie le processus de demande de devis.',
      // Sponsor 5
      sponsor5Service: 'Agence de marketing',
      sponsor5Desc: 'Ramzi Kerouicha offre des services complets de marketing numérique et de stratégie de marque. Il a choisi Synapse pour développer une plateforme numérique de pointe qui présente son expertise en marketing et attire des clients de grande valeur.',
      sponsor5Why: 'A collaboré avec Synapse pour créer une présence en ligne sophistiquée qui démontre ses compétences en marketing et convertit les visiteurs en clients.',
    },
    contactPage: {
      badge: 'Contactez-nous',
      title1: 'Démarrons une',
      title2: 'conversation',
      subtitle: 'Vous avez un projet en tête? Nous aimerions en savoir plus. Envoyez-nous un message et nous vous répondrons dans les 24 heures.',
      formTitle: 'Envoyez-nous un message',
      formSubtitle: 'Remplissez le formulaire ci-dessous et nous vous répondrons sous peu.',
      formNameLabel: 'Nom complet *',
      formNamePlaceholder: 'Jean Dupont',
      formEmailLabel: 'Adresse e-mail *',
      formEmailPlaceholder: 'jean@exemple.com',
      formCompanyLabel: 'Nom de l\'entreprise',
      formCompanyPlaceholder: 'Votre entreprise',
      formPhoneLabel: 'Numéro de téléphone',
      formPhonePlaceholder: '+1 (555) 123-4567',
      formServiceLabel: 'Service souhaité *',
      formServicePlaceholder: 'Sélectionnez un service',
      formServiceWeb: 'Développement web',
      formServiceMobile: 'Développement d\'applications mobiles',
      formServiceBranding: 'Branding numérique',
      formServiceStrategy: 'Stratégie numérique',
      formServiceEcommerce: 'E-commerce',
      formServiceOther: 'Autre',
      formBudgetLabel: 'Budget du projet',
      formBudgetPlaceholder: 'Sélectionnez une fourchette de budget',
      formBudget1: '5 000 $ - 10 000 $',
      formBudget2: '10 000 $ - 25 000 $',
      formBudget3: '25 000 $ - 50 000 $',
      formBudget4: '50 000 $+',
      formMessageLabel: 'Détails du projet *',
      formMessagePlaceholder: 'Parlez-nous de votre projet...',
      formSubmitButton: 'Envoyer le message',
      formSuccessTitle: 'Message envoyé!',
      formSuccessSubtitle: 'Nous vous répondrons dans les 24 heures.',
      emailTitle: 'Envoyez-nous un e-mail',
      emailContent: 'contact@madebysynapse.com',
      emailDescription: 'Envoyez-nous un e-mail à tout moment',
      phoneTitle: '',
      phoneContent: '',
      phoneDescription: '',
      locationTitle: 'Visitez-nous',
      locationContent: 'Montréal, Québec',
      locationDescription: 'Venez nous dire bonjour à notre bureau',
      hoursTitle: 'Heures d\'ouverture',
      hoursMonFri: 'Lundi - vendredi',
      hoursMonFriTime: '9h00 - 18h00',
      hoursSat: 'Samedi',
      hoursSatTime: '10h00 - 16h00',
      hoursSun: 'Dimanche',
      hoursSunTime: 'Fermé',
      hoursEmergency: 'Support d\'urgence disponible 24/7',
      mapTitle: 'Notre emplacement',
      mapSubtitle: 'Montréal, Québec',
      faqBadge: 'FAQ',
      faqTitle1: 'Questions',
      faqTitle2: 'fréquemment posées',
      faqSubtitle: 'Trouvez des réponses aux questions courantes sur nos services et notre façon de travailler',
      faqQ1: 'Quels services propose Synapse?',
      faqA1: 'Synapse est une agence numérique complète spécialisée dans le développement web et logiciel, la conception UI/UX, le branding et la transformation numérique. Nous aidons les entreprises à concevoir, construire et développer des produits numériques fiables, sécurisés et adaptés aux besoins réels de l\'entreprise.',
      faqQ2: 'Avec quels types d\'entreprises travaillez-vous?',
      faqA2: 'Nous travaillons avec des startups, des petites et moyennes entreprises et des entreprises en croissance dans différents secteurs. Que vous lanciez un nouveau produit ou amélioriez un système existant, nous adaptons notre processus à vos objectifs, votre budget et vos exigences techniques.',
      faqQ3: 'Comment un projet démarre-t-il généralement?',
      faqA3: 'Chaque projet commence par un court appel de découverte. Nous prenons le temps de comprendre vos objectifs, vos défis et vos utilisateurs, puis nous proposons une solution claire, un calendrier et les prochaines étapes avant tout développement.',
      faqQ4: 'Combien de temps prend un projet typique?',
      faqA4: 'Les délais de projet varient en fonction de la complexité et de la portée. Un site web simple ou une refonte peut prendre quelques semaines, tandis que des solutions logicielles personnalisées plus importantes peuvent prendre plusieurs mois. Après notre consultation initiale, nous fournissons un calendrier détaillé pour que vous sachiez toujours à quoi vous attendre.',
      faqQ5: 'Combien coûtent vos services?',
      faqA5: 'Nos prix sont basés sur la portée, les fonctionnalités et la complexité technique de chaque projet. Nous n\'utilisons pas de forfaits universels. Après avoir examiné vos besoins, nous fournissons une proposition transparente et sur mesure.',
      faqQ6: 'Serai-je impliqué pendant le projet?',
      faqA6: 'Oui. Nous croyons en une collaboration étroite et une communication claire. Vous recevrez des mises à jour régulières, des aperçus de conception et des opportunités de fournir des commentaires tout au long du processus.',
      faqQ7: 'Offrez-vous un support continu après la fin du projet?',
      faqA7: 'Oui. Nous offrons des options de maintenance et de support pour garantir que votre site web ou produit numérique reste sécurisé, stable et à jour après le lancement.',
      faqQ8: 'Pouvez-vous travailler avec notre site web ou système existant?',
      faqA8: 'Absolument. Nous pouvons améliorer, reconcevoir ou étendre des plateformes, sites web et systèmes logiciels existants, tout en minimisant les perturbations de vos opérations commerciales.',
      faqQ9: 'Aidez-vous avec la conception ainsi que le développement?',
      faqA9: 'Oui. Notre équipe s\'occupe à la fois de la conception et du développement, garantissant que votre produit numérique est visuellement fort, convivial et techniquement robuste.',
      faqQ10: 'Comment puis-je commencer avec Synapse?',
      faqA10: 'Remplissez simplement le formulaire de contact ci-dessus et parlez-nous de votre projet. Notre équipe vous répondra pour planifier une courte consultation et discuter de la meilleure voie à suivre.',
    },
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    // Provide a silent fallback for hot-reload scenarios during development
    return {
      language: 'en' as Language,
      setLanguage: () => {},
      t: (key: string) => key,
    };
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};